apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
  labels:
   app: todos
  namespace: proyecto
spec:
  replicas: 1
  #strategy:
  #  type: RollingUpdate
  selector:
    matchLabels:
         app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
     containers:
     - name: todos
       image: andres192715/todos-api:0.0.1
       env:
        - name: TODO_API_PORT
          value: "8082"
        - name: JWT_SECRET
          value: "PRFT"
        - name: REDIS_HOST
          value: "127.0.0.1"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: "log_channel"
       ports:
        - containerPort: 8082
---

apiVersion: v1
kind: Service
metadata:
 name: todos
 namespace: proyecto
 labels:
  app: todos
spec:
 type: ClusterIP
 ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
 selector:
  app: todos